### ISSUE TITLE
TWRC_FAILURE

### ISSUE THREAD

**Issue by MeTe-30** [Asprise/scannerjs.javascript-scanner-access-in-browsers-chrome-ie.scanner.js#1]
Hi, 
While trying to scan documents with i1220 Kodak Scanner, i'm facing with this error:
`scanner.js:1 Uncaught <error: failed to open data source: TWRC_FAILURE>`
I haven't any problem with these modules:
http://demo.leadtools.com/javascript/ScanningDemo
https://www.dynamsoft.com/demo/dwt/online_demo_scan.aspx
Any idea?

**Comment by Asprise** [comment]
One possible reason is the device was used by another program/service. To be sure, you may check the log files at: %AppData%\ScanApp2

**Comment by Asprise** [comment]
Closed as no response received. Please raise another issue if you still have trouble with it.
